CREATE DATABASE bamazon;

USE bamazon;

CREATE TABLE products (
ITEM_ID INT(11) AUTO_INCREMENT NOT NULL,
PRODUCT_NAME VARCHAR(45) NOT NULL,
DEPARTMENT_NAME VARCHAR(45) NOT NULL,
PRICE DECIMAL(4,2) NOT NULL,
STOCK_QUANTITY INT (11) NOT NULL,
PRIMARY KEY (ITEM_ID) )

ENGINE=innoDB DEFAULT CHARSET=UTF8;

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (1, "CD PLAYER", "ELECTRONICS", 79.99, 10);

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (2, "COTTON SOCKS 10PK", "MEN'S CLOTHING", 7.99, 100); 

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (3, "SATIN PINK NIGHTIE", "WOMEN'S CLOTHING", 24.99, 20);

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (4, "MEN'S WORK BOOTS", "FOOTWEAR", 29.99, 10);

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (5, "UPRIGHT VACUUM", "HOUSEWARES", 69.99, 5);

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (6, "BOYS BMX BICYCLE", "TOYS", 129.99, 6);

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (7, "STROLLER", "BABY", 49.99, 4);

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (8, "WINDEX 32oz", "CLEANING SUPPLIES", 8.99, 40);

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (9, "CAR BATTERY", "AUTO", 119.99, 5);

INSERT INTO products (ITEM_ID, PRODUCT_NAME, DEPARTMENT_NAME, PRICE, STOCK_QUANTITY) 
VALUES (10, "WOMEN'S ANTI-PERSPIRANT", "HEALTH & BEAUTY", 6.99, 50);

SELECT * FROM products;